### ISSUE TITLE
JSON to step

### ISSUE THREAD

**Issue by natarius** [aljoshakoecher/STEP-to-JSON#9]
Got any plans to offer it the other way around?

I am looking for a js library to create step files

**Comment by aljoshakoecher** [comment]
Hey @natarius, to be honest: No...
I created this as a simple, tiny library to parse the assembly structure (parent / child components) of a STEP file into JSON. I mainly created this library to then map the JSON into an OWL ontology inside a web application.
But feel free to take what you can use out of this project - but I guess it's not much 😄.

If you're looking for some kind of converter between one format and STEP: Do you know [assimp](https://github.com/assimp/assimp)? It's a pretty powerful library to convert between various 3D file formats. Maybe there is a js library for another format and you can then use assimp to convert it to STEP...

**Comment by lamgianguyen** [comment]
Hey sir, I want to convert STEP to Json that I can compare it with another step file for my project, is that possible?

**Comment by aljoshakoecher** [comment]
Hey @nguyentrumcoin! Sure, this little utility library converts the assembly structure (parent / child components) from STEP into a JSON representation. You could convert this, but please note that this is just a tiny part of the whole STEP specification. Other elements are currently not converted to JSON.
I am now closing this pretty old issue. If you need more help, please open a new issue.
